- name: create isutrain directory
  file: path="/home/isucon/isutrain" state=directory mode=0755 owner=isucon group=isucon
  tags: challenge

- name: copy webapp
  unarchive: src=webapp.tar.gz dest=/home/isucon/isutrain/ owner=isucon group=isucon
  tags:
    - challenge
    - webapp
  notify: restart python

- name: create systemd services
  template: src=isutrain.service dest="/etc/systemd/system/isutrain-{{ item }}.service" owner=root group=root mode=0644
  with_items:
    - python
  tags: challenge
  notify: systemctl daemon-reload

- name: enabled default service
  service: name=isutrain-python enabled=yes state=started
  tags: challenge

- name: install nginx
  apt: name=nginx state=latest update_cache=yes
  tags: challenge

- name: nginx config
  template: src=nginx/default dest=/etc/nginx/sites-available/default owner=root group=root mode=0644
  tags: challenge
  notify: reload nginx

- name: create ssl directory
  file: path=/etc/nginx/keys state=directory owner=root group=root mode=0700
  tags: challenge

- name: copy ssl keys
  copy: src="certs/isucon9.hinatan.net/{{ item }}" dest="/etc/nginx/keys/{{ item }}" owner=root group=root mode=0600
  tags: challenge
  with_items:
    - fullchain.pem
    - privkey.pem
  notify: reload nginx

- name: robots.txt
  template: src=nginx/robots.txt dest=/var/www/html/robots.txt owner=root group=root mode=0644
  tags: challenge


- name: copy frontend
  unarchive: src=frontend.tar.gz dest=/var/www/html/ owner=www-data group=www-data
  tags:
    - challenge
    - frontend
